services:
  api:
    image: "danuk/shm-api:${CORE_VERSION}"
    pull_policy: always
    restart: always
    depends_on:
      - core
  core:
    image: "danuk/shm-core:${CORE_VERSION}"
    pull_policy: always
    restart: always
    environment:
      #DEBUG: DEBUG
      TZ: ${TZ}
      LANG: C.UTF-8
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
  spool:
    image: "danuk/shm-core:${CORE_VERSION}"
    pull_policy: always
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    environment:
      #DEBUG: ERROR
      TZ: ${TZ}
      LANG: C.UTF-8
      SHM_ROLE: "spool"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
  admin:
    image: "danuk/shm-admin:${ADMIN_VERSION}"
    pull_policy: always
    restart: always
    environment:
      SHM_HOST: http://api
    ports:
      - "0.0.0.0:8081:80"
    depends_on:
      - api
  client:
    image: "danuk/shm-client:${CLIENT_VERSION}"
    pull_policy: always
    restart: always
    environment:
      SHM_HOST: http://api
#    volumes:
#      - ./styles-alternative.css:/app/assets/css/styles-alternative.css
#      - ./head.html:/app/ssi/head.html
#      - ./body.html:/app/ssi/body.html
    ports:
      - "0.0.0.0:8082:80"
    depends_on:
      - api
  mysql:
    image: "mysql:lts"
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - "mysql-data:/var/lib/mysql"
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3306:3306"
volumes:
  mysql-data:
    driver: local

